dist: trusty

jobs:
  include:
    - stage: build
      script:
      - git clone https://github.com/hari-karthig/hello-makisu.git 
      - cd hello-makisu
      - docker build -t harikarthi/hello-makisu:travis .
      - cd docker-makisu
      - docker build -t harikarthi/makisu:travis .
      - docker images

