apiVersion: v1
kind: Pod
metadata:
  labels:
    app: cicd
  name: makisu
spec:
  containers:
  - image: jenkinsci/jnlp-slave:3.27-1-alpine
    imagePullPolicy: IfNotPresent
    name: jnlp
    resources: {}
  - image: hariyaa/makisu-sh:1.0
    imagePullPolicy: Always
    name: makisu
    tty: true
    resources: {}
    volumeMounts:
    - name: registry-config
      mountPath: /registry-config
  volumes:
  - name: registry-config
    secret:
      secretName: docker-registry-config
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
